### ISSUE TITLE
Shows other app's icon for .zip files

### ISSUE THREAD

**Issue by SanmayJoshi** [veniosg/Dir#101]
Dir has the ability to compress a file or folder to .zip and to decompress a .zip file. As Dir handles .zip files this excellently, I think Dir might use an icon which represents a compressed file for .zip files, rather than using other apps' icons for the same. :)

**Comment by veniosg** [comment]
The problem is that despite Dir being able to run this operation on zip files, it is not a native "open" experience like Rar for example. I'm afraid I'll keep this as is until Dir supports opening zip files as if they were normal folders (which is not planned atm) as that would otherwise break the user's expectations for what would happen on click.

**Comment by SanmayJoshi** [comment]
I agree. I'll open an issue for browsing zip files like folders so that anyone interested in it may provide their inputs.

Cheers :)
