### ISSUE TITLE
when I open a picture on dir file manger with simple gallery another image is displayed

### ISSUE THREAD

**Issue by kodeblacc** [veniosg/Dir#117]
#### Expected behavior
I expected that when I open a picture from Dir file manager with simple gallery I'll be able to view the selected picture

#### Actual behavior
When I perform the action stated above, the gallery app opens another picture.

#### How to reproduce
- download the apps (dir file manager and simple gallery) from fdroid
- launch the app
- allow all permissions if prompted
- open a picture from dir file manager with simple gallery.
- another picture will be viewed
<hr>

* Device:  infinix note 4
* Operating system: android 8.0
* Software version: Dir file manager v1.5.5
Simple Gallery v3.6.0

#### Recording Of The Bug
https://vimeo.com/260931234

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/when-i-open-a-picture-on-dir-file-manger-with-simple-gallery-another-image-is-displayed">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by veniosg** [comment]
Given that when Gallery is initially launched you can see its title on the top right showing the right filename, and only afterwards switching to the webm file, and that's there's no sign of this bug existing when using other gallery apps, I am fairly certain that this is actually an issue with the gallery app instead of Dir.
