### ISSUE TITLE
Support for Android TV 

### ISSUE THREAD

**Issue by platinumapps** [veniosg/Dir#24]
Any chance of an update that supports Android TV? I know I could just sideload it and see how it goes, but it'd certainly be handy if I could just install it via Google Play as handling files on the Nvidia Shield TV isn't great and the other 3rd party I'm using isn't nearly as nice looking as Dir.

**Comment by veniosg** [comment]
Unfortunately I don't have a device to test this on and get a feel for the system's conventions. As I wouldn't want to release a half baked update or one that doesn't fit the TV experience, there are currently no plans of supporting Android TV. 
That being said, since Dir is forked off OI File Manager which supports Google TV and I've taken every care to keep the UI as dynamic as possible, I believe that if you just grab the apk and sideload it to your device it'll be functionally fine and usable enough.
