### ISSUE TITLE
Modifying navigation drawer

### ISSUE THREAD

**Issue by SanmayJoshi** [veniosg/Dir#46]
Hey George,

I had some suggestions regarding nav. drawer-

>Increasing height of cover (background image) in navigation drawer

I think (pretty personal opinion), maybe the navigation drawer would look even better if the cover image for `Bookmark` text was a bit more in height, the way it is in Google apps. I think it's more cozy that way.

>Appearance of bookmarks

The bookmarks in nav. drawer appear the same way folders appear in app. Maybe, assigning a different icon for bookmarks and having them appear the same way as different fragments (Settings, About) would make nav. drawer look more consistent.

>Material style icon for New(Plus) and Edit(Pencil)

I think, Dir would look even better, if it had the floating circular icon, as in Gmail for compose, for New and Edit(when selected). The same New(Plus) icon may convert into Edit(Pencil) icon on selecting a file or folder. 

>Adding an option to create a file alongside the option to create folder

As of now, we are able to create new folder with the new folder icon. I think (taking into consideration  above suggestion) adding facility to create new file after tapping the plus icon may add an extra feature.
Many apps have the floating icon, which shows options(which appear as circles above the tapped icon which turns into cross, well you get the point :wink:) when tapped. Maybe the plus icon could be like that.

I'm referencing issue #45 as it is related to this issue.

I hope I didn't do a lot of mutter mutter. :laughing: 
<br>
Thanks

**Comment by veniosg** [comment]
I'm afraid I'm going to disappoint you on this issue. Specifically:

>Increasing height of cover (background image) in navigation drawer
>Appearance of bookmarks

For these two, I've replied in #45.

> Material style icon for New(Plus) and Edit(Pencil)

I'm assuming you're referring to the Floating Action Button. According to the [Material design guidelines](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button), "A floating action button represents the primary action in an application". Dir being a file manager, there is no inherent primary action (or at least it's not "Create directory"). The Pencil/operations action could be a candidate but I'm afraid it'll make for a unnecessarily separated set of actions. I've actually been thinking about completely disbanding the operations "group" and having them on the top level when long pressing, as quite a few users have had trouble finding these; making it a FAB will make that transition even harder. 

> Adding an option to create a file alongside the option to create folder

I was actually thinking about doing this during the Material redesign, but even if there's a "create file" action, it's not apparent what type that file should be. Given the options, I opted to not add it at all to avoid having a half-baked implementation and UX. (FWIW, given the time constraints, the options where either creating only text files, which would probably also need a text editor implementation, or allowing any filetype but being unable to edit almost all of them in-app).

As a side note, (and this is the case both for the FAB and the nav drawer), many apps try to fit these patterns everywhere, sometimes worsening the UX, just because they feel it's a must-have for Material design apps. In designing Dir I've deliberately avoided using standard components that make no sense for the app's purpose and use case only to make Dir feel more "standard". Hence the lack of some ubiquitous components/patterns :) 

Hope this makes sense,
George.

**Comment by SanmayJoshi** [comment]
Hey George,

It's very nice to have well reasoned reply from you. Thanks for that.

I don't mean to be persistent here, but think I need to clarify some issues listed above, that I think, I didn't explain well.

>Appearance of bookmarks

I think one may want to name a bookmark something different than the original name of the folder. So, maybe it might be that bookmarks and their original folder could be discriminated. This is also the reason I mentioned making bookmarks look similar to other fragments in nav drawer.

>Adding an option to create a file alongside the option to create folder

By allowing users to create new file, I meant to allow them to create any kind of new file. When a user shall type name for that file, the user would type the name with extension, which is how the file type shall be determined. Many apps do similar, I guess.

All other issues mentioned above are perfectly handled by you. Thanks for such a well thought reply.

**Comment by veniosg** [comment]
No worries, thanks for the update.

About the bookmarks, what do you mean by making them look similar to other fragments? They're actually using the same code behind the scenes at the moment. In regards to renaming them, this actually could be done fairly easily using the current interface and code. 

In regards to the file creation option, I haven't used other file managers for a long time ago. Would you happen to know how the most popular ones handle this? If it turns out that enough popular ones do it that it's expected, I would be up for adding this generic "create file" option, and let opening the file worry the apps we delegate to.
