### ISSUE TITLE
Icons of files

### ISSUE THREAD

**Issue by SanmayJoshi** [veniosg/Dir#47]
Hey George,

As of right now, app shows icons of files as per the app which opens them. It is perfect. 

The Dir app shows a circle around the folder icon and file icon. In this process, the file icons are cropped. So, when at times, the icon of a file isn't symmetric, it doesn't look as good as the app does :wink:. So, maybe, rather than circle(for file icons only, folder icons look perfect) if Dir used only, say, an underline and left some space between underline and icon(so that there is enough breathing room for icons, well you know that better than me), it might look prettier.

Thanks.

**Comment by veniosg** [comment]
Let me see if I understand this correctly: 
The issue you're describing is only present for image and video thumbnails. App icons, default file icons, folder icons all show correctly. Is that true? 

That being said I'm not sure I understand what the issue is. If you mean it is the icons are circles and therefore cropped, this might be an issue of form over function. I think a fair compromise would be (if possible) to try and have the icon take up the whole circle (no gray circle behind the thumbnail). That being said I'm not sure this is possible without messing with the "app icon" thumbnails, because their icons share the same code and padding and they would end up outside the circle but can't be cropped. 

Anyway, lmk what the issue is so we can have a better look.

**Comment by veniosg** [comment]
Hey, check this planned change - it should cover that use case! 
https://github.com/veniosg/Dir/issues/74

**Comment by johndoe71rus** [comment]
Yes, it's useful. But the grid is suitable for folders with uniform content. For example, the Downloads folder may contain different files. In this case, the list is the best choice.

**Comment by veniosg** [comment]
Maybe a hybrid approach where videos and images are always attached as a
grid at the bottom of the list would be the best of both worlds?

>

**Comment by johndoe71rus** [comment]
made a collage for illustration. In my opinion, these previews look better.
https://i.imgur.com/v9FSifo.jpg
can be trivial, but clearer

**Comment by SanmayJoshi** [comment]
Just caught up with discussion. What @johndoe71rus has illustrated in above comment seems perfectly correcting the issue I meant. Thanks both for following up!

**Comment by veniosg** [comment]
I agree that this looks better in terms of the preview, but the ui feels more cluttered and busy as a whole - ideally all the icons would have the same shape. I'm not against everything being rounded squares but I'd have to try it and see how that looks. 
FWIW I'd still prefer a clearer separation between regular thumbnails and previews given the different needs for each.

**Comment by johndoe71rus** [comment]
disable preview. Draw round icon with text extention file.
example https://s3.envato.com/files/12271566/1File%20document%20icons.jpg
