### ISSUE TITLE
Publishing app on f-droid

### ISSUE THREAD

**Issue by SanmayJoshi** [veniosg/Dir#50]
Hey George,

F-droid is known to have pretty strict inclusion policy, and Dir satisfies it perfectly. Having app in f-droid is a proof of app having noble intents. I think seeing Dir in f-droid would be awesome, right?

Links that might help:

[Docs](https://f-droid.org/docs/) has all links listed, still I'm listing some imp ones.

* [Inclusion Policy](https://f-droid.org/wiki/page/Inclusion_Policy)
* [Inclusion How-To](https://f-droid.org/wiki/page/Inclusion_How-To)
* [Submitting to F-Droid: Quick Start Guide](https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/)
* [Build Metadata Reference](https://f-droid.org/docs/Build_Metadata_Reference/)

**Comment by veniosg** [comment]
My main issue is that we'd lose control over apk signing, and I'm not sure I trust F-Droid enough - especially not seeing much of a point in being exposed. 

That being said, I'll leave this issue open in case someone's interested in setting it up and/or knows more around what it would involve.

**Comment by Primokorn** [comment]
I think you can trust F-Droid since they build FLOSS apps for years and for free!
They *just* compile apps from repositories.

They are all volunteers and it's a small team. Everything is not perfect (even with GAFAM lol) but we can definitively trust them.

As said by email I submitted Dir: https://gitlab.com/fdroid/rfp/issues/394
Feel free to post questions or cancel my submission if you want.

F-Droid is widely used by Android users who care about their privacy and security. It's also a useful platform to download app udpates or discover new FLOSS apps.

**Comment by veniosg** [comment]
Thanks for providing more details and going through the submission process! Let's not cancel, afaict this won't do any harm :)

**Comment by veniosg** [comment]
Seems like the work for the rfp is done, so I'm closing this ticket. fwiw I still can't see it inside the fdroid app but I trust their processes

**Comment by adisib** [comment]
I've seen it listed under latest, but there isn't an icon for it.

**Comment by veniosg** [comment]
Wow, it's up now indeed. For some reason the version is reported as 1.5.1,
does it just build on every master push? :|
