### ISSUE TITLE
Announcing on xda-forums

### ISSUE THREAD

**Issue by SanmayJoshi** [veniosg/Dir#51]
Hey George,

If you would like to increase the number of users of Dir, I think announcing Dir on XDA-Forum might be a good idea. I would recommend publishing app on f-droid before announcing on xda (issue #50), as having app on f-droid would make xda users believe more on intents of app.

**Comment by veniosg** [comment]
Thanks for the suggestion. I'm not too worried about increasing users, but it wouldn't hurt letting people know :) 
I agree that people there might value the app being on f-droid, but based on the comments in #50 though, I think it'd be better to just post the app in xda and see what happens, rather than wait for that f-droid inclusion. Worst case, I can post an update once the fdroid release happens. 

P.S. Is this the place you were thinking? xda sure has changed :) https://forum.xda-developers.com/monetization/your-portfolio

**Comment by veniosg** [comment]
Seems like you have to have at least 10 replies to post links - and I don't have any expertise in modding etc to get to that number - so I'm unable to post.
